# Generated by Django 5.2.1 on 2025-05-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('staff', 'Staff'), ('admin', 'Admin')], default='supplier', max_length=10),
        ),
    ]
