# Generated by Django 5.2.1 on 2025-06-03 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_name_product_product_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('sourcing_status', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('remarks', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='FormRowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('rfq_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_templates', to='forms.rfq_form')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_fixed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rfq_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='forms.rfq_form')),
            ],
        ),
        migrations.CreateModel(
            name='FormRowResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('row_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='forms.formrowtemplate')),
            ],
            options={
                'unique_together': {('row_template', 'supplier_user')},
            },
        ),
    ]
