# Generated by Django 5.2.3 on 2025-06-18 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formrowresponse',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='SupplierFormRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('rfq_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_remarks', to='forms.rfq_form')),
                ('supplier_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
